### ISSUE TITLE
resonators~ hangs 32-bit windows

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-Externs#42] opened 2015-07-11 05:39 UTC
Symptom: Max hangs, then windows asks user to force quit.

Steps:
- open resonators~.maxhelp
- turn audio on

Regression: I'm not aware of any strange settings in my installation of Max, which I believe is vanilla out of the box.

{
    "version" : "Version 7.0.4 (cbb83ff3) (32-bit windows)",
    "platform" : "windows",
    "arch" : "x86",
    "osversion" : "Microsoft Windows 7 Professional Service Pack 1 (build 7601), 64-bit",
    "samplerate" : 44100,
    "iovs" : 512,
    "sigvs" : 512,
    "scheduler_in_audio_interrupt" : "off",
    "audio_drivername" : "ad_mme",
    "audio_driver_subname" : "",
    "license" : "permanent full",
    "machine_id" : "e4aa7fe204b153cdc6434f60592253e0",
    "eventinterval" : 2,
    "overdrive" : "on",
    "mixerparallel" : "off",
    "mixercrossfade" : 0,
    "mixerlatency" : 30.0,
    "mixerramptime" : 10.0,
    "videoengine" : "qt",
}

**Comment by equilet** [comment] 2015-07-11 05:40
I double-checked my scheduler settings against my documented factory defaults, and all looks fine there.

**Comment by ilzxc** [comment] 2015-07-11 23:46
I looked into this -- the "double" mode that called the dresonators dsp routines **was never actually supported properly on Windows** -- old 32-bit versions do not work on Windows with the `double` flag.

This means that we may not utilize the same bit of code for Mac (supporting 64-bit) and Windows (not supporting 64-bit) -- so I'm working on a work-around that will ensure the correct, stable, tested old build will be included in the current 32-bit Windows release.

Do not close this issue.

**Comment by ramagottfried** [comment] 2017-10-04 09:58
can't reproduce this running Max 32bit on Windows 10 -- however I don't see any commits related to this after July 9, 2015. Maybe this is only on Windows 7?

**Comment by ramagottfried** [comment] 2018-01-02 16:33
tested again on windows 10 with max 32bit , no hang, all seems fine. if anyone can reproduce this please reopen the issue.  also if you have a windows 7 machine, please test to see if you can reproduce this.

**Closed by ramagottfried** 2018-01-02 16:33 UTC
Labels: bug, testing
